apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mosquitto-mqtt
  title: Mosquitto MQTT Broker
  description: Deploy a Mosquitto MQTT broker using Docker Compose
spec:
  owner: your-team
  type: service

  parameters:
    - title: Mosquitto Deployment Details
      required:
        - deployment_name
        - mqtt_port
        - remote_host
      properties:
        deployment_name:
          title: Deployment Name
          type: string
          description: Name for your deployment instance
        mqtt_port:
          title: MQTT Port
          type: number
          default: 1883
          description: Port to expose MQTT broker
        remote_host:
          title: Remote Host
          type: string
          description: IP or hostname of the remote PC
        ssh_user:
          title: SSH Username
          type: string
          default: root
          description: SSH username to connect to the remote host

  steps:
    - id: fetch-template
      name: Fetch Template Files
      action: fetch:template
      input:
        url: https://github.com/mig-migazi/backstage-templates/tree/main/templates/mosquitto-template
        values:
          deployment_name: ${{ parameters.deployment_name }}
          mqtt_port: ${{ parameters.mqtt_port }}

    - id: deploy
      name: Deploy to Remote Host
      action: shell:script
      input:
        script: |
          scp -r ./ ${{ parameters.ssh_user }}@${{ parameters.remote_host }}:~/mosquitto-${{ parameters.deployment_name }}
          ssh ${{ parameters.ssh_user }}@${{ parameters.remote_host }} << 'EOF'
            cd ~/mosquitto-${{ parameters.deployment_name }}
            docker compose up -d
          EOF
